# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/neimog/Documents/Git/pd-simpl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/neimog/Documents/Git/pd-simpl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all:
	$(CMAKE_COMMAND) -E cmake_progress_start /home/neimog/Documents/Git/pd-simpl/CMakeFiles /home/neimog/Documents/Git/pd-simpl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/neimog/Documents/Git/pd-simpl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

#=============================================================================
# Target rules for targets named pd-simpl

# Build rule for target.
pd-simpl:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pd-simpl
.PHONY : pd-simpl

# fast build rule for target.
pd-simpl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pd-simpl.dir/build.make CMakeFiles/pd-simpl.dir/build
.PHONY : pd-simpl/fast

#=============================================================================
# Target rules for targets named simpl

# Build rule for target.
simpl:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simpl
.PHONY : simpl

# fast build rule for target.
simpl/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/simpl/CMakeFiles/simpl.dir/build.make Libraries/simpl/CMakeFiles/simpl.dir/build
.PHONY : simpl/fast

Sources/pd-simpl.o: Sources/pd-simpl.cpp.o
.PHONY : Sources/pd-simpl.o

# target to build an object file
Sources/pd-simpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pd-simpl.dir/build.make CMakeFiles/pd-simpl.dir/Sources/pd-simpl.cpp.o
.PHONY : Sources/pd-simpl.cpp.o

Sources/pd-simpl.i: Sources/pd-simpl.cpp.i
.PHONY : Sources/pd-simpl.i

# target to preprocess a source file
Sources/pd-simpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pd-simpl.dir/build.make CMakeFiles/pd-simpl.dir/Sources/pd-simpl.cpp.i
.PHONY : Sources/pd-simpl.cpp.i

Sources/pd-simpl.s: Sources/pd-simpl.cpp.s
.PHONY : Sources/pd-simpl.s

# target to generate assembly for a file
Sources/pd-simpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pd-simpl.dir/build.make CMakeFiles/pd-simpl.dir/Sources/pd-simpl.cpp.s
.PHONY : Sources/pd-simpl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... pd-simpl"
	@echo "... simpl"
	@echo "... Sources/pd-simpl.o"
	@echo "... Sources/pd-simpl.i"
	@echo "... Sources/pd-simpl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

